<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sparkplug_b.proto

namespace Org\Eclipse\Tahu\Protobuf\Payload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>org.eclipse.tahu.protobuf.Payload.Metric</code>
 */
class Metric extends \Google\Protobuf\Internal\Message
{
    /**
     * Metric name - should only be included on birth
     *
     * Generated from protobuf field <code>optional string name = 1;</code>
     */
    protected $name = null;
    /**
     * Metric alias - tied to name on birth and included in all later DATA messages
     *
     * Generated from protobuf field <code>optional uint64 alias = 2;</code>
     */
    protected $alias = null;
    /**
     * Timestamp associated with data acquisition time
     *
     * Generated from protobuf field <code>optional uint64 timestamp = 3;</code>
     */
    protected $timestamp = null;
    /**
     * DataType of the metric/tag value
     *
     * Generated from protobuf field <code>optional uint32 datatype = 4;</code>
     */
    protected $datatype = null;
    /**
     * If this is historical data and should not update real time tag
     *
     * Generated from protobuf field <code>optional bool is_historical = 5;</code>
     */
    protected $is_historical = null;
    /**
     * Tells consuming clients such as MQTT Engine to not store this as a tag
     *
     * Generated from protobuf field <code>optional bool is_transient = 6;</code>
     */
    protected $is_transient = null;
    /**
     * If this is null - explicitly say so rather than using -1, false, etc for some datatypes.
     *
     * Generated from protobuf field <code>optional bool is_null = 7;</code>
     */
    protected $is_null = null;
    /**
     * Metadata for the payload
     *
     * Generated from protobuf field <code>optional .org.eclipse.tahu.protobuf.Payload.MetaData metadata = 8;</code>
     */
    protected $metadata = null;
    /**
     * Generated from protobuf field <code>optional .org.eclipse.tahu.protobuf.Payload.PropertySet properties = 9;</code>
     */
    protected $properties = null;
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Metric name - should only be included on birth
     *     @type int|string $alias
     *           Metric alias - tied to name on birth and included in all later DATA messages
     *     @type int|string $timestamp
     *           Timestamp associated with data acquisition time
     *     @type int $datatype
     *           DataType of the metric/tag value
     *     @type bool $is_historical
     *           If this is historical data and should not update real time tag
     *     @type bool $is_transient
     *           Tells consuming clients such as MQTT Engine to not store this as a tag
     *     @type bool $is_null
     *           If this is null - explicitly say so rather than using -1, false, etc for some datatypes.
     *     @type \Org\Eclipse\Tahu\Protobuf\Payload\MetaData $metadata
     *           Metadata for the payload
     *     @type \Org\Eclipse\Tahu\Protobuf\Payload\PropertySet $properties
     *     @type int $int_value
     *     @type int|string $long_value
     *     @type float $float_value
     *     @type float $double_value
     *     @type bool $boolean_value
     *     @type string $string_value
     *     @type string $bytes_value
     *           Bytes, File
     *     @type \Org\Eclipse\Tahu\Protobuf\Payload\DataSet $dataset_value
     *     @type \Org\Eclipse\Tahu\Protobuf\Payload\Template $template_value
     *     @type \Org\Eclipse\Tahu\Protobuf\Payload\Metric\MetricValueExtension $extension_value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SparkplugB::initOnce();
        parent::__construct($data);
    }

    /**
     * Metric name - should only be included on birth
     *
     * Generated from protobuf field <code>optional string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->name) ? $this->name : '';
    }

    public function hasName()
    {
        return isset($this->name);
    }

    public function clearName()
    {
        unset($this->name);
    }

    /**
     * Metric name - should only be included on birth
     *
     * Generated from protobuf field <code>optional string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Metric alias - tied to name on birth and included in all later DATA messages
     *
     * Generated from protobuf field <code>optional uint64 alias = 2;</code>
     * @return int|string
     */
    public function getAlias()
    {
        return isset($this->alias) ? $this->alias : 0;
    }

    public function hasAlias()
    {
        return isset($this->alias);
    }

    public function clearAlias()
    {
        unset($this->alias);
    }

    /**
     * Metric alias - tied to name on birth and included in all later DATA messages
     *
     * Generated from protobuf field <code>optional uint64 alias = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAlias($var)
    {
        GPBUtil::checkUint64($var);
        $this->alias = $var;

        return $this;
    }

    /**
     * Timestamp associated with data acquisition time
     *
     * Generated from protobuf field <code>optional uint64 timestamp = 3;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return isset($this->timestamp) ? $this->timestamp : 0;
    }

    public function hasTimestamp()
    {
        return isset($this->timestamp);
    }

    public function clearTimestamp()
    {
        unset($this->timestamp);
    }

    /**
     * Timestamp associated with data acquisition time
     *
     * Generated from protobuf field <code>optional uint64 timestamp = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * DataType of the metric/tag value
     *
     * Generated from protobuf field <code>optional uint32 datatype = 4;</code>
     * @return int
     */
    public function getDatatype()
    {
        return isset($this->datatype) ? $this->datatype : 0;
    }

    public function hasDatatype()
    {
        return isset($this->datatype);
    }

    public function clearDatatype()
    {
        unset($this->datatype);
    }

    /**
     * DataType of the metric/tag value
     *
     * Generated from protobuf field <code>optional uint32 datatype = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setDatatype($var)
    {
        GPBUtil::checkUint32($var);
        $this->datatype = $var;

        return $this;
    }

    /**
     * If this is historical data and should not update real time tag
     *
     * Generated from protobuf field <code>optional bool is_historical = 5;</code>
     * @return bool
     */
    public function getIsHistorical()
    {
        return isset($this->is_historical) ? $this->is_historical : false;
    }

    public function hasIsHistorical()
    {
        return isset($this->is_historical);
    }

    public function clearIsHistorical()
    {
        unset($this->is_historical);
    }

    /**
     * If this is historical data and should not update real time tag
     *
     * Generated from protobuf field <code>optional bool is_historical = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsHistorical($var)
    {
        GPBUtil::checkBool($var);
        $this->is_historical = $var;

        return $this;
    }

    /**
     * Tells consuming clients such as MQTT Engine to not store this as a tag
     *
     * Generated from protobuf field <code>optional bool is_transient = 6;</code>
     * @return bool
     */
    public function getIsTransient()
    {
        return isset($this->is_transient) ? $this->is_transient : false;
    }

    public function hasIsTransient()
    {
        return isset($this->is_transient);
    }

    public function clearIsTransient()
    {
        unset($this->is_transient);
    }

    /**
     * Tells consuming clients such as MQTT Engine to not store this as a tag
     *
     * Generated from protobuf field <code>optional bool is_transient = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsTransient($var)
    {
        GPBUtil::checkBool($var);
        $this->is_transient = $var;

        return $this;
    }

    /**
     * If this is null - explicitly say so rather than using -1, false, etc for some datatypes.
     *
     * Generated from protobuf field <code>optional bool is_null = 7;</code>
     * @return bool
     */
    public function getIsNull()
    {
        return isset($this->is_null) ? $this->is_null : false;
    }

    public function hasIsNull()
    {
        return isset($this->is_null);
    }

    public function clearIsNull()
    {
        unset($this->is_null);
    }

    /**
     * If this is null - explicitly say so rather than using -1, false, etc for some datatypes.
     *
     * Generated from protobuf field <code>optional bool is_null = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsNull($var)
    {
        GPBUtil::checkBool($var);
        $this->is_null = $var;

        return $this;
    }

    /**
     * Metadata for the payload
     *
     * Generated from protobuf field <code>optional .org.eclipse.tahu.protobuf.Payload.MetaData metadata = 8;</code>
     * @return \Org\Eclipse\Tahu\Protobuf\Payload\MetaData|null
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    public function hasMetadata()
    {
        return isset($this->metadata);
    }

    public function clearMetadata()
    {
        unset($this->metadata);
    }

    /**
     * Metadata for the payload
     *
     * Generated from protobuf field <code>optional .org.eclipse.tahu.protobuf.Payload.MetaData metadata = 8;</code>
     * @param \Org\Eclipse\Tahu\Protobuf\Payload\MetaData $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkMessage($var, \Org\Eclipse\Tahu\Protobuf\Payload\MetaData::class);
        $this->metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .org.eclipse.tahu.protobuf.Payload.PropertySet properties = 9;</code>
     * @return \Org\Eclipse\Tahu\Protobuf\Payload\PropertySet|null
     */
    public function getProperties()
    {
        return $this->properties;
    }

    public function hasProperties()
    {
        return isset($this->properties);
    }

    public function clearProperties()
    {
        unset($this->properties);
    }

    /**
     * Generated from protobuf field <code>optional .org.eclipse.tahu.protobuf.Payload.PropertySet properties = 9;</code>
     * @param \Org\Eclipse\Tahu\Protobuf\Payload\PropertySet $var
     * @return $this
     */
    public function setProperties($var)
    {
        GPBUtil::checkMessage($var, \Org\Eclipse\Tahu\Protobuf\Payload\PropertySet::class);
        $this->properties = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 int_value = 10;</code>
     * @return int
     */
    public function getIntValue()
    {
        return $this->readOneof(10);
    }

    public function hasIntValue()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>uint32 int_value = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setIntValue($var)
    {
        GPBUtil::checkUint32($var);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 long_value = 11;</code>
     * @return int|string
     */
    public function getLongValue()
    {
        return $this->readOneof(11);
    }

    public function hasLongValue()
    {
        return $this->hasOneof(11);
    }

    /**
     * Generated from protobuf field <code>uint64 long_value = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLongValue($var)
    {
        GPBUtil::checkUint64($var);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>float float_value = 12;</code>
     * @return float
     */
    public function getFloatValue()
    {
        return $this->readOneof(12);
    }

    public function hasFloatValue()
    {
        return $this->hasOneof(12);
    }

    /**
     * Generated from protobuf field <code>float float_value = 12;</code>
     * @param float $var
     * @return $this
     */
    public function setFloatValue($var)
    {
        GPBUtil::checkFloat($var);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>double double_value = 13;</code>
     * @return float
     */
    public function getDoubleValue()
    {
        return $this->readOneof(13);
    }

    public function hasDoubleValue()
    {
        return $this->hasOneof(13);
    }

    /**
     * Generated from protobuf field <code>double double_value = 13;</code>
     * @param float $var
     * @return $this
     */
    public function setDoubleValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->writeOneof(13, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool boolean_value = 14;</code>
     * @return bool
     */
    public function getBooleanValue()
    {
        return $this->readOneof(14);
    }

    public function hasBooleanValue()
    {
        return $this->hasOneof(14);
    }

    /**
     * Generated from protobuf field <code>bool boolean_value = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setBooleanValue($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(14, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string string_value = 15;</code>
     * @return string
     */
    public function getStringValue()
    {
        return $this->readOneof(15);
    }

    public function hasStringValue()
    {
        return $this->hasOneof(15);
    }

    /**
     * Generated from protobuf field <code>string string_value = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setStringValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(15, $var);

        return $this;
    }

    /**
     * Bytes, File
     *
     * Generated from protobuf field <code>bytes bytes_value = 16;</code>
     * @return string
     */
    public function getBytesValue()
    {
        return $this->readOneof(16);
    }

    public function hasBytesValue()
    {
        return $this->hasOneof(16);
    }

    /**
     * Bytes, File
     *
     * Generated from protobuf field <code>bytes bytes_value = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setBytesValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(16, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.org.eclipse.tahu.protobuf.Payload.DataSet dataset_value = 17;</code>
     * @return \Org\Eclipse\Tahu\Protobuf\Payload\DataSet|null
     */
    public function getDatasetValue()
    {
        return $this->readOneof(17);
    }

    public function hasDatasetValue()
    {
        return $this->hasOneof(17);
    }

    /**
     * Generated from protobuf field <code>.org.eclipse.tahu.protobuf.Payload.DataSet dataset_value = 17;</code>
     * @param \Org\Eclipse\Tahu\Protobuf\Payload\DataSet $var
     * @return $this
     */
    public function setDatasetValue($var)
    {
        GPBUtil::checkMessage($var, \Org\Eclipse\Tahu\Protobuf\Payload\DataSet::class);
        $this->writeOneof(17, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.org.eclipse.tahu.protobuf.Payload.Template template_value = 18;</code>
     * @return \Org\Eclipse\Tahu\Protobuf\Payload\Template|null
     */
    public function getTemplateValue()
    {
        return $this->readOneof(18);
    }

    public function hasTemplateValue()
    {
        return $this->hasOneof(18);
    }

    /**
     * Generated from protobuf field <code>.org.eclipse.tahu.protobuf.Payload.Template template_value = 18;</code>
     * @param \Org\Eclipse\Tahu\Protobuf\Payload\Template $var
     * @return $this
     */
    public function setTemplateValue($var)
    {
        GPBUtil::checkMessage($var, \Org\Eclipse\Tahu\Protobuf\Payload\Template::class);
        $this->writeOneof(18, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.org.eclipse.tahu.protobuf.Payload.Metric.MetricValueExtension extension_value = 19;</code>
     * @return \Org\Eclipse\Tahu\Protobuf\Payload\Metric\MetricValueExtension|null
     */
    public function getExtensionValue()
    {
        return $this->readOneof(19);
    }

    public function hasExtensionValue()
    {
        return $this->hasOneof(19);
    }

    /**
     * Generated from protobuf field <code>.org.eclipse.tahu.protobuf.Payload.Metric.MetricValueExtension extension_value = 19;</code>
     * @param \Org\Eclipse\Tahu\Protobuf\Payload\Metric\MetricValueExtension $var
     * @return $this
     */
    public function setExtensionValue($var)
    {
        GPBUtil::checkMessage($var, \Org\Eclipse\Tahu\Protobuf\Payload\Metric\MetricValueExtension::class);
        $this->writeOneof(19, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Metric::class, \Org\Eclipse\Tahu\Protobuf\Payload_Metric::class);

