<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sparkplug_b.proto

namespace Org\Eclipse\Tahu\Protobuf\Payload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>org.eclipse.tahu.protobuf.Payload.PropertySet</code>
 */
class PropertySet extends \Google\Protobuf\Internal\Message
{
    /**
     * Names of the properties
     *
     * Generated from protobuf field <code>repeated string keys = 1;</code>
     */
    private $keys;
    /**
     * Generated from protobuf field <code>repeated .org.eclipse.tahu.protobuf.Payload.PropertyValue values = 2;</code>
     */
    private $values;
    /**
     * extensions                      3 to max; // For proto2
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any extensions = 3;</code>
     */
    private $extensions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $keys
     *           Names of the properties
     *     @type array<\Org\Eclipse\Tahu\Protobuf\Payload\PropertyValue>|\Google\Protobuf\Internal\RepeatedField $values
     *     @type array<\Google\Protobuf\Any>|\Google\Protobuf\Internal\RepeatedField $extensions
     *           extensions                      3 to max; // For proto2
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SparkplugB::initOnce();
        parent::__construct($data);
    }

    /**
     * Names of the properties
     *
     * Generated from protobuf field <code>repeated string keys = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * Names of the properties
     *
     * Generated from protobuf field <code>repeated string keys = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->keys = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .org.eclipse.tahu.protobuf.Payload.PropertyValue values = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Generated from protobuf field <code>repeated .org.eclipse.tahu.protobuf.Payload.PropertyValue values = 2;</code>
     * @param array<\Org\Eclipse\Tahu\Protobuf\Payload\PropertyValue>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Org\Eclipse\Tahu\Protobuf\Payload\PropertyValue::class);
        $this->values = $arr;

        return $this;
    }

    /**
     * extensions                      3 to max; // For proto2
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any extensions = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    /**
     * extensions                      3 to max; // For proto2
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any extensions = 3;</code>
     * @param array<\Google\Protobuf\Any>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExtensions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Any::class);
        $this->extensions = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PropertySet::class, \Org\Eclipse\Tahu\Protobuf\Payload_PropertySet::class);

