<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sparkplug_b.proto

namespace Org\Eclipse\Tahu\Protobuf\Payload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>org.eclipse.tahu.protobuf.Payload.Template</code>
 */
class Template extends \Google\Protobuf\Internal\Message
{
    /**
     * The version of the Template to prevent mismatches
     *
     * Generated from protobuf field <code>optional string version = 1;</code>
     */
    protected $version = null;
    /**
     * Each metric includes a name, datatype, and optionally a value
     *
     * Generated from protobuf field <code>repeated .org.eclipse.tahu.protobuf.Payload.Metric metrics = 2;</code>
     */
    private $metrics;
    /**
     * Generated from protobuf field <code>repeated .org.eclipse.tahu.protobuf.Payload.Template.Parameter parameters = 3;</code>
     */
    private $parameters;
    /**
     * MUST be a reference to a template definition if this is an instance (i.e. the name of the template definition) - MUST be omitted for template definitions
     *
     * Generated from protobuf field <code>optional string template_ref = 4;</code>
     */
    protected $template_ref = null;
    /**
     * Generated from protobuf field <code>optional bool is_definition = 5;</code>
     */
    protected $is_definition = null;
    /**
     * extensions                      6 to max;		// For proto2
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any extensions = 6;</code>
     */
    private $extensions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $version
     *           The version of the Template to prevent mismatches
     *     @type array<\Org\Eclipse\Tahu\Protobuf\Payload\Metric>|\Google\Protobuf\Internal\RepeatedField $metrics
     *           Each metric includes a name, datatype, and optionally a value
     *     @type array<\Org\Eclipse\Tahu\Protobuf\Payload\Template\Parameter>|\Google\Protobuf\Internal\RepeatedField $parameters
     *     @type string $template_ref
     *           MUST be a reference to a template definition if this is an instance (i.e. the name of the template definition) - MUST be omitted for template definitions
     *     @type bool $is_definition
     *     @type array<\Google\Protobuf\Any>|\Google\Protobuf\Internal\RepeatedField $extensions
     *           extensions                      6 to max;		// For proto2
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SparkplugB::initOnce();
        parent::__construct($data);
    }

    /**
     * The version of the Template to prevent mismatches
     *
     * Generated from protobuf field <code>optional string version = 1;</code>
     * @return string
     */
    public function getVersion()
    {
        return isset($this->version) ? $this->version : '';
    }

    public function hasVersion()
    {
        return isset($this->version);
    }

    public function clearVersion()
    {
        unset($this->version);
    }

    /**
     * The version of the Template to prevent mismatches
     *
     * Generated from protobuf field <code>optional string version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     * Each metric includes a name, datatype, and optionally a value
     *
     * Generated from protobuf field <code>repeated .org.eclipse.tahu.protobuf.Payload.Metric metrics = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMetrics()
    {
        return $this->metrics;
    }

    /**
     * Each metric includes a name, datatype, and optionally a value
     *
     * Generated from protobuf field <code>repeated .org.eclipse.tahu.protobuf.Payload.Metric metrics = 2;</code>
     * @param array<\Org\Eclipse\Tahu\Protobuf\Payload\Metric>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMetrics($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Org\Eclipse\Tahu\Protobuf\Payload\Metric::class);
        $this->metrics = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .org.eclipse.tahu.protobuf.Payload.Template.Parameter parameters = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    /**
     * Generated from protobuf field <code>repeated .org.eclipse.tahu.protobuf.Payload.Template.Parameter parameters = 3;</code>
     * @param array<\Org\Eclipse\Tahu\Protobuf\Payload\Template\Parameter>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setParameters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Org\Eclipse\Tahu\Protobuf\Payload\Template\Parameter::class);
        $this->parameters = $arr;

        return $this;
    }

    /**
     * MUST be a reference to a template definition if this is an instance (i.e. the name of the template definition) - MUST be omitted for template definitions
     *
     * Generated from protobuf field <code>optional string template_ref = 4;</code>
     * @return string
     */
    public function getTemplateRef()
    {
        return isset($this->template_ref) ? $this->template_ref : '';
    }

    public function hasTemplateRef()
    {
        return isset($this->template_ref);
    }

    public function clearTemplateRef()
    {
        unset($this->template_ref);
    }

    /**
     * MUST be a reference to a template definition if this is an instance (i.e. the name of the template definition) - MUST be omitted for template definitions
     *
     * Generated from protobuf field <code>optional string template_ref = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTemplateRef($var)
    {
        GPBUtil::checkString($var, True);
        $this->template_ref = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool is_definition = 5;</code>
     * @return bool
     */
    public function getIsDefinition()
    {
        return isset($this->is_definition) ? $this->is_definition : false;
    }

    public function hasIsDefinition()
    {
        return isset($this->is_definition);
    }

    public function clearIsDefinition()
    {
        unset($this->is_definition);
    }

    /**
     * Generated from protobuf field <code>optional bool is_definition = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDefinition($var)
    {
        GPBUtil::checkBool($var);
        $this->is_definition = $var;

        return $this;
    }

    /**
     * extensions                      6 to max;		// For proto2
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any extensions = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    /**
     * extensions                      6 to max;		// For proto2
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any extensions = 6;</code>
     * @param array<\Google\Protobuf\Any>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExtensions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Any::class);
        $this->extensions = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Template::class, \Org\Eclipse\Tahu\Protobuf\Payload_Template::class);

