/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sparkplug_b.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sparkplug_b.pb-c.h"
void   org__eclipse__tahu__protobuf__payload__template__parameter__parameter_value_extension__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter__ParameterValueExtension         *message)
{
  static const Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter__ParameterValueExtension init_value = ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__TEMPLATE__PARAMETER__PARAMETER_VALUE_EXTENSION__INIT;
  *message = init_value;
}
void   org__eclipse__tahu__protobuf__payload__template__parameter__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter         *message)
{
  static const Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter init_value = ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__TEMPLATE__PARAMETER__INIT;
  *message = init_value;
}
void   org__eclipse__tahu__protobuf__payload__template__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__Template         *message)
{
  static const Org__Eclipse__Tahu__Protobuf__Payload__Template init_value = ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__TEMPLATE__INIT;
  *message = init_value;
}
void   org__eclipse__tahu__protobuf__payload__data_set__data_set_value__data_set_value_extension__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue__DataSetValueExtension         *message)
{
  static const Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue__DataSetValueExtension init_value = ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__DATA_SET__DATA_SET_VALUE__DATA_SET_VALUE_EXTENSION__INIT;
  *message = init_value;
}
void   org__eclipse__tahu__protobuf__payload__data_set__data_set_value__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue         *message)
{
  static const Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue init_value = ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__DATA_SET__DATA_SET_VALUE__INIT;
  *message = init_value;
}
void   org__eclipse__tahu__protobuf__payload__data_set__row__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__DataSet__Row         *message)
{
  static const Org__Eclipse__Tahu__Protobuf__Payload__DataSet__Row init_value = ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__DATA_SET__ROW__INIT;
  *message = init_value;
}
void   org__eclipse__tahu__protobuf__payload__data_set__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__DataSet         *message)
{
  static const Org__Eclipse__Tahu__Protobuf__Payload__DataSet init_value = ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__DATA_SET__INIT;
  *message = init_value;
}
void   org__eclipse__tahu__protobuf__payload__property_value__property_value_extension__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue__PropertyValueExtension         *message)
{
  static const Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue__PropertyValueExtension init_value = ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__PROPERTY_VALUE__PROPERTY_VALUE_EXTENSION__INIT;
  *message = init_value;
}
void   org__eclipse__tahu__protobuf__payload__property_value__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue         *message)
{
  static const Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue init_value = ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__PROPERTY_VALUE__INIT;
  *message = init_value;
}
void   org__eclipse__tahu__protobuf__payload__property_set__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__PropertySet         *message)
{
  static const Org__Eclipse__Tahu__Protobuf__Payload__PropertySet init_value = ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__PROPERTY_SET__INIT;
  *message = init_value;
}
void   org__eclipse__tahu__protobuf__payload__property_set_list__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__PropertySetList         *message)
{
  static const Org__Eclipse__Tahu__Protobuf__Payload__PropertySetList init_value = ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__PROPERTY_SET_LIST__INIT;
  *message = init_value;
}
void   org__eclipse__tahu__protobuf__payload__meta_data__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__MetaData         *message)
{
  static const Org__Eclipse__Tahu__Protobuf__Payload__MetaData init_value = ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__META_DATA__INIT;
  *message = init_value;
}
void   org__eclipse__tahu__protobuf__payload__metric__metric_value_extension__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__Metric__MetricValueExtension         *message)
{
  static const Org__Eclipse__Tahu__Protobuf__Payload__Metric__MetricValueExtension init_value = ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__METRIC__METRIC_VALUE_EXTENSION__INIT;
  *message = init_value;
}
void   org__eclipse__tahu__protobuf__payload__metric__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__Metric         *message)
{
  static const Org__Eclipse__Tahu__Protobuf__Payload__Metric init_value = ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__METRIC__INIT;
  *message = init_value;
}
void   org__eclipse__tahu__protobuf__payload__init
                     (Org__Eclipse__Tahu__Protobuf__Payload         *message)
{
  static const Org__Eclipse__Tahu__Protobuf__Payload init_value = ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__INIT;
  *message = init_value;
}
size_t org__eclipse__tahu__protobuf__payload__get_packed_size
                     (const Org__Eclipse__Tahu__Protobuf__Payload *message)
{
  assert(message->base.descriptor == &org__eclipse__tahu__protobuf__payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t org__eclipse__tahu__protobuf__payload__pack
                     (const Org__Eclipse__Tahu__Protobuf__Payload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &org__eclipse__tahu__protobuf__payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t org__eclipse__tahu__protobuf__payload__pack_to_buffer
                     (const Org__Eclipse__Tahu__Protobuf__Payload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &org__eclipse__tahu__protobuf__payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Org__Eclipse__Tahu__Protobuf__Payload *
       org__eclipse__tahu__protobuf__payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Org__Eclipse__Tahu__Protobuf__Payload *)
     protobuf_c_message_unpack (&org__eclipse__tahu__protobuf__payload__descriptor,
                                allocator, len, data);
}
void   org__eclipse__tahu__protobuf__payload__free_unpacked
                     (Org__Eclipse__Tahu__Protobuf__Payload *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &org__eclipse__tahu__protobuf__payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define org__eclipse__tahu__protobuf__payload__template__parameter__parameter_value_extension__field_descriptors NULL
#define org__eclipse__tahu__protobuf__payload__template__parameter__parameter_value_extension__field_indices_by_name NULL
#define org__eclipse__tahu__protobuf__payload__template__parameter__parameter_value_extension__number_ranges NULL
const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__template__parameter__parameter_value_extension__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "org.eclipse.tahu.protobuf.Payload.Template.Parameter.ParameterValueExtension",
  "ParameterValueExtension",
  "Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter__ParameterValueExtension",
  "org.eclipse.tahu.protobuf",
  sizeof(Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter__ParameterValueExtension),
  0,
  org__eclipse__tahu__protobuf__payload__template__parameter__parameter_value_extension__field_descriptors,
  org__eclipse__tahu__protobuf__payload__template__parameter__parameter_value_extension__field_indices_by_name,
  0,  org__eclipse__tahu__protobuf__payload__template__parameter__parameter_value_extension__number_ranges,
  (ProtobufCMessageInit) org__eclipse__tahu__protobuf__payload__template__parameter__parameter_value_extension__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor org__eclipse__tahu__protobuf__payload__template__parameter__field_descriptors[9] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter, has_type),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int_value",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter, int_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "long_value",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter, long_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "float_value",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter, float_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "double_value",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter, double_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "boolean_value",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter, boolean_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_value",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter, string_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extension_value",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter, extension_value),
    &org__eclipse__tahu__protobuf__payload__template__parameter__parameter_value_extension__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned org__eclipse__tahu__protobuf__payload__template__parameter__field_indices_by_name[] = {
  6,   /* field[6] = boolean_value */
  5,   /* field[5] = double_value */
  8,   /* field[8] = extension_value */
  4,   /* field[4] = float_value */
  2,   /* field[2] = int_value */
  3,   /* field[3] = long_value */
  0,   /* field[0] = name */
  7,   /* field[7] = string_value */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange org__eclipse__tahu__protobuf__payload__template__parameter__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__template__parameter__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "org.eclipse.tahu.protobuf.Payload.Template.Parameter",
  "Parameter",
  "Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter",
  "org.eclipse.tahu.protobuf",
  sizeof(Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter),
  9,
  org__eclipse__tahu__protobuf__payload__template__parameter__field_descriptors,
  org__eclipse__tahu__protobuf__payload__template__parameter__field_indices_by_name,
  1,  org__eclipse__tahu__protobuf__payload__template__parameter__number_ranges,
  (ProtobufCMessageInit) org__eclipse__tahu__protobuf__payload__template__parameter__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor org__eclipse__tahu__protobuf__payload__template__field_descriptors[5] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metrics",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template, n_metrics),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template, metrics),
    &org__eclipse__tahu__protobuf__payload__metric__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parameters",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template, n_parameters),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template, parameters),
    &org__eclipse__tahu__protobuf__payload__template__parameter__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "template_ref",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template, template_ref),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_definition",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template, has_is_definition),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Template, is_definition),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned org__eclipse__tahu__protobuf__payload__template__field_indices_by_name[] = {
  4,   /* field[4] = is_definition */
  1,   /* field[1] = metrics */
  2,   /* field[2] = parameters */
  3,   /* field[3] = template_ref */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange org__eclipse__tahu__protobuf__payload__template__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__template__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "org.eclipse.tahu.protobuf.Payload.Template",
  "Template",
  "Org__Eclipse__Tahu__Protobuf__Payload__Template",
  "org.eclipse.tahu.protobuf",
  sizeof(Org__Eclipse__Tahu__Protobuf__Payload__Template),
  5,
  org__eclipse__tahu__protobuf__payload__template__field_descriptors,
  org__eclipse__tahu__protobuf__payload__template__field_indices_by_name,
  1,  org__eclipse__tahu__protobuf__payload__template__number_ranges,
  (ProtobufCMessageInit) org__eclipse__tahu__protobuf__payload__template__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define org__eclipse__tahu__protobuf__payload__data_set__data_set_value__data_set_value_extension__field_descriptors NULL
#define org__eclipse__tahu__protobuf__payload__data_set__data_set_value__data_set_value_extension__field_indices_by_name NULL
#define org__eclipse__tahu__protobuf__payload__data_set__data_set_value__data_set_value_extension__number_ranges NULL
const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__data_set__data_set_value__data_set_value_extension__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "org.eclipse.tahu.protobuf.Payload.DataSet.DataSetValue.DataSetValueExtension",
  "DataSetValueExtension",
  "Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue__DataSetValueExtension",
  "org.eclipse.tahu.protobuf",
  sizeof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue__DataSetValueExtension),
  0,
  org__eclipse__tahu__protobuf__payload__data_set__data_set_value__data_set_value_extension__field_descriptors,
  org__eclipse__tahu__protobuf__payload__data_set__data_set_value__data_set_value_extension__field_indices_by_name,
  0,  org__eclipse__tahu__protobuf__payload__data_set__data_set_value__data_set_value_extension__number_ranges,
  (ProtobufCMessageInit) org__eclipse__tahu__protobuf__payload__data_set__data_set_value__data_set_value_extension__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor org__eclipse__tahu__protobuf__payload__data_set__data_set_value__field_descriptors[7] =
{
  {
    "int_value",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue, int_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "long_value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue, long_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "float_value",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue, float_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "double_value",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue, double_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "boolean_value",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue, boolean_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_value",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue, string_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extension_value",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue, extension_value),
    &org__eclipse__tahu__protobuf__payload__data_set__data_set_value__data_set_value_extension__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned org__eclipse__tahu__protobuf__payload__data_set__data_set_value__field_indices_by_name[] = {
  4,   /* field[4] = boolean_value */
  3,   /* field[3] = double_value */
  6,   /* field[6] = extension_value */
  2,   /* field[2] = float_value */
  0,   /* field[0] = int_value */
  1,   /* field[1] = long_value */
  5,   /* field[5] = string_value */
};
static const ProtobufCIntRange org__eclipse__tahu__protobuf__payload__data_set__data_set_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__data_set__data_set_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "org.eclipse.tahu.protobuf.Payload.DataSet.DataSetValue",
  "DataSetValue",
  "Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue",
  "org.eclipse.tahu.protobuf",
  sizeof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue),
  7,
  org__eclipse__tahu__protobuf__payload__data_set__data_set_value__field_descriptors,
  org__eclipse__tahu__protobuf__payload__data_set__data_set_value__field_indices_by_name,
  1,  org__eclipse__tahu__protobuf__payload__data_set__data_set_value__number_ranges,
  (ProtobufCMessageInit) org__eclipse__tahu__protobuf__payload__data_set__data_set_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor org__eclipse__tahu__protobuf__payload__data_set__row__field_descriptors[1] =
{
  {
    "elements",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet__Row, n_elements),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet__Row, elements),
    &org__eclipse__tahu__protobuf__payload__data_set__data_set_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned org__eclipse__tahu__protobuf__payload__data_set__row__field_indices_by_name[] = {
  0,   /* field[0] = elements */
};
static const ProtobufCIntRange org__eclipse__tahu__protobuf__payload__data_set__row__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__data_set__row__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "org.eclipse.tahu.protobuf.Payload.DataSet.Row",
  "Row",
  "Org__Eclipse__Tahu__Protobuf__Payload__DataSet__Row",
  "org.eclipse.tahu.protobuf",
  sizeof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet__Row),
  1,
  org__eclipse__tahu__protobuf__payload__data_set__row__field_descriptors,
  org__eclipse__tahu__protobuf__payload__data_set__row__field_indices_by_name,
  1,  org__eclipse__tahu__protobuf__payload__data_set__row__number_ranges,
  (ProtobufCMessageInit) org__eclipse__tahu__protobuf__payload__data_set__row__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor org__eclipse__tahu__protobuf__payload__data_set__field_descriptors[4] =
{
  {
    "num_of_columns",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet, has_num_of_columns),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet, num_of_columns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "columns",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet, n_columns),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet, columns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "types",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet, n_types),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet, types),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rows",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet, n_rows),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet, rows),
    &org__eclipse__tahu__protobuf__payload__data_set__row__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned org__eclipse__tahu__protobuf__payload__data_set__field_indices_by_name[] = {
  1,   /* field[1] = columns */
  0,   /* field[0] = num_of_columns */
  3,   /* field[3] = rows */
  2,   /* field[2] = types */
};
static const ProtobufCIntRange org__eclipse__tahu__protobuf__payload__data_set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__data_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "org.eclipse.tahu.protobuf.Payload.DataSet",
  "DataSet",
  "Org__Eclipse__Tahu__Protobuf__Payload__DataSet",
  "org.eclipse.tahu.protobuf",
  sizeof(Org__Eclipse__Tahu__Protobuf__Payload__DataSet),
  4,
  org__eclipse__tahu__protobuf__payload__data_set__field_descriptors,
  org__eclipse__tahu__protobuf__payload__data_set__field_indices_by_name,
  1,  org__eclipse__tahu__protobuf__payload__data_set__number_ranges,
  (ProtobufCMessageInit) org__eclipse__tahu__protobuf__payload__data_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define org__eclipse__tahu__protobuf__payload__property_value__property_value_extension__field_descriptors NULL
#define org__eclipse__tahu__protobuf__payload__property_value__property_value_extension__field_indices_by_name NULL
#define org__eclipse__tahu__protobuf__payload__property_value__property_value_extension__number_ranges NULL
const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__property_value__property_value_extension__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "org.eclipse.tahu.protobuf.Payload.PropertyValue.PropertyValueExtension",
  "PropertyValueExtension",
  "Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue__PropertyValueExtension",
  "org.eclipse.tahu.protobuf",
  sizeof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue__PropertyValueExtension),
  0,
  org__eclipse__tahu__protobuf__payload__property_value__property_value_extension__field_descriptors,
  org__eclipse__tahu__protobuf__payload__property_value__property_value_extension__field_indices_by_name,
  0,  org__eclipse__tahu__protobuf__payload__property_value__property_value_extension__number_ranges,
  (ProtobufCMessageInit) org__eclipse__tahu__protobuf__payload__property_value__property_value_extension__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor org__eclipse__tahu__protobuf__payload__property_value__field_descriptors[11] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, has_type),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_null",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, has_is_null),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, is_null),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int_value",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, int_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "long_value",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, long_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "float_value",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, float_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "double_value",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, double_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "boolean_value",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, boolean_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_value",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, string_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "propertyset_value",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, propertyset_value),
    &org__eclipse__tahu__protobuf__payload__property_set__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "propertysets_value",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, propertysets_value),
    &org__eclipse__tahu__protobuf__payload__property_set_list__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extension_value",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue, extension_value),
    &org__eclipse__tahu__protobuf__payload__property_value__property_value_extension__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned org__eclipse__tahu__protobuf__payload__property_value__field_indices_by_name[] = {
  6,   /* field[6] = boolean_value */
  5,   /* field[5] = double_value */
  10,   /* field[10] = extension_value */
  4,   /* field[4] = float_value */
  2,   /* field[2] = int_value */
  1,   /* field[1] = is_null */
  3,   /* field[3] = long_value */
  8,   /* field[8] = propertyset_value */
  9,   /* field[9] = propertysets_value */
  7,   /* field[7] = string_value */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange org__eclipse__tahu__protobuf__payload__property_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__property_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "org.eclipse.tahu.protobuf.Payload.PropertyValue",
  "PropertyValue",
  "Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue",
  "org.eclipse.tahu.protobuf",
  sizeof(Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue),
  11,
  org__eclipse__tahu__protobuf__payload__property_value__field_descriptors,
  org__eclipse__tahu__protobuf__payload__property_value__field_indices_by_name,
  1,  org__eclipse__tahu__protobuf__payload__property_value__number_ranges,
  (ProtobufCMessageInit) org__eclipse__tahu__protobuf__payload__property_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor org__eclipse__tahu__protobuf__payload__property_set__field_descriptors[2] =
{
  {
    "keys",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertySet, n_keys),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertySet, keys),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "values",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertySet, n_values),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertySet, values),
    &org__eclipse__tahu__protobuf__payload__property_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned org__eclipse__tahu__protobuf__payload__property_set__field_indices_by_name[] = {
  0,   /* field[0] = keys */
  1,   /* field[1] = values */
};
static const ProtobufCIntRange org__eclipse__tahu__protobuf__payload__property_set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__property_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "org.eclipse.tahu.protobuf.Payload.PropertySet",
  "PropertySet",
  "Org__Eclipse__Tahu__Protobuf__Payload__PropertySet",
  "org.eclipse.tahu.protobuf",
  sizeof(Org__Eclipse__Tahu__Protobuf__Payload__PropertySet),
  2,
  org__eclipse__tahu__protobuf__payload__property_set__field_descriptors,
  org__eclipse__tahu__protobuf__payload__property_set__field_indices_by_name,
  1,  org__eclipse__tahu__protobuf__payload__property_set__number_ranges,
  (ProtobufCMessageInit) org__eclipse__tahu__protobuf__payload__property_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor org__eclipse__tahu__protobuf__payload__property_set_list__field_descriptors[1] =
{
  {
    "propertyset",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertySetList, n_propertyset),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__PropertySetList, propertyset),
    &org__eclipse__tahu__protobuf__payload__property_set__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned org__eclipse__tahu__protobuf__payload__property_set_list__field_indices_by_name[] = {
  0,   /* field[0] = propertyset */
};
static const ProtobufCIntRange org__eclipse__tahu__protobuf__payload__property_set_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__property_set_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "org.eclipse.tahu.protobuf.Payload.PropertySetList",
  "PropertySetList",
  "Org__Eclipse__Tahu__Protobuf__Payload__PropertySetList",
  "org.eclipse.tahu.protobuf",
  sizeof(Org__Eclipse__Tahu__Protobuf__Payload__PropertySetList),
  1,
  org__eclipse__tahu__protobuf__payload__property_set_list__field_descriptors,
  org__eclipse__tahu__protobuf__payload__property_set_list__field_indices_by_name,
  1,  org__eclipse__tahu__protobuf__payload__property_set_list__number_ranges,
  (ProtobufCMessageInit) org__eclipse__tahu__protobuf__payload__property_set_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor org__eclipse__tahu__protobuf__payload__meta_data__field_descriptors[8] =
{
  {
    "is_multi_part",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__MetaData, has_is_multi_part),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__MetaData, is_multi_part),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content_type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__MetaData, content_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__MetaData, has_size),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__MetaData, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__MetaData, has_seq),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__MetaData, seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "file_name",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__MetaData, file_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "file_type",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__MetaData, file_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "md5",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__MetaData, md5),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__MetaData, description),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned org__eclipse__tahu__protobuf__payload__meta_data__field_indices_by_name[] = {
  1,   /* field[1] = content_type */
  7,   /* field[7] = description */
  4,   /* field[4] = file_name */
  5,   /* field[5] = file_type */
  0,   /* field[0] = is_multi_part */
  6,   /* field[6] = md5 */
  3,   /* field[3] = seq */
  2,   /* field[2] = size */
};
static const ProtobufCIntRange org__eclipse__tahu__protobuf__payload__meta_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__meta_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "org.eclipse.tahu.protobuf.Payload.MetaData",
  "MetaData",
  "Org__Eclipse__Tahu__Protobuf__Payload__MetaData",
  "org.eclipse.tahu.protobuf",
  sizeof(Org__Eclipse__Tahu__Protobuf__Payload__MetaData),
  8,
  org__eclipse__tahu__protobuf__payload__meta_data__field_descriptors,
  org__eclipse__tahu__protobuf__payload__meta_data__field_indices_by_name,
  1,  org__eclipse__tahu__protobuf__payload__meta_data__number_ranges,
  (ProtobufCMessageInit) org__eclipse__tahu__protobuf__payload__meta_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define org__eclipse__tahu__protobuf__payload__metric__metric_value_extension__field_descriptors NULL
#define org__eclipse__tahu__protobuf__payload__metric__metric_value_extension__field_indices_by_name NULL
#define org__eclipse__tahu__protobuf__payload__metric__metric_value_extension__number_ranges NULL
const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__metric__metric_value_extension__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "org.eclipse.tahu.protobuf.Payload.Metric.MetricValueExtension",
  "MetricValueExtension",
  "Org__Eclipse__Tahu__Protobuf__Payload__Metric__MetricValueExtension",
  "org.eclipse.tahu.protobuf",
  sizeof(Org__Eclipse__Tahu__Protobuf__Payload__Metric__MetricValueExtension),
  0,
  org__eclipse__tahu__protobuf__payload__metric__metric_value_extension__field_descriptors,
  org__eclipse__tahu__protobuf__payload__metric__metric_value_extension__field_indices_by_name,
  0,  org__eclipse__tahu__protobuf__payload__metric__metric_value_extension__number_ranges,
  (ProtobufCMessageInit) org__eclipse__tahu__protobuf__payload__metric__metric_value_extension__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor org__eclipse__tahu__protobuf__payload__metric__field_descriptors[19] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alias",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, has_alias),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, alias),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, has_timestamp),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "datatype",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, has_datatype),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, datatype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_historical",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, has_is_historical),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, is_historical),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_transient",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, has_is_transient),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, is_transient),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_null",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, has_is_null),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, is_null),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metadata",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, metadata),
    &org__eclipse__tahu__protobuf__payload__meta_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "properties",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, properties),
    &org__eclipse__tahu__protobuf__payload__property_set__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int_value",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, int_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "long_value",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, long_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "float_value",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, float_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "double_value",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, double_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "boolean_value",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, boolean_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_value",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, string_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bytes_value",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, bytes_value),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dataset_value",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, dataset_value),
    &org__eclipse__tahu__protobuf__payload__data_set__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "template_value",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, template_value),
    &org__eclipse__tahu__protobuf__payload__template__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extension_value",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, value_case),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload__Metric, extension_value),
    &org__eclipse__tahu__protobuf__payload__metric__metric_value_extension__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned org__eclipse__tahu__protobuf__payload__metric__field_indices_by_name[] = {
  1,   /* field[1] = alias */
  13,   /* field[13] = boolean_value */
  15,   /* field[15] = bytes_value */
  16,   /* field[16] = dataset_value */
  3,   /* field[3] = datatype */
  12,   /* field[12] = double_value */
  18,   /* field[18] = extension_value */
  11,   /* field[11] = float_value */
  9,   /* field[9] = int_value */
  4,   /* field[4] = is_historical */
  6,   /* field[6] = is_null */
  5,   /* field[5] = is_transient */
  10,   /* field[10] = long_value */
  7,   /* field[7] = metadata */
  0,   /* field[0] = name */
  8,   /* field[8] = properties */
  14,   /* field[14] = string_value */
  17,   /* field[17] = template_value */
  2,   /* field[2] = timestamp */
};
static const ProtobufCIntRange org__eclipse__tahu__protobuf__payload__metric__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 19 }
};
const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__metric__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "org.eclipse.tahu.protobuf.Payload.Metric",
  "Metric",
  "Org__Eclipse__Tahu__Protobuf__Payload__Metric",
  "org.eclipse.tahu.protobuf",
  sizeof(Org__Eclipse__Tahu__Protobuf__Payload__Metric),
  19,
  org__eclipse__tahu__protobuf__payload__metric__field_descriptors,
  org__eclipse__tahu__protobuf__payload__metric__field_indices_by_name,
  1,  org__eclipse__tahu__protobuf__payload__metric__number_ranges,
  (ProtobufCMessageInit) org__eclipse__tahu__protobuf__payload__metric__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor org__eclipse__tahu__protobuf__payload__field_descriptors[5] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload, has_timestamp),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metrics",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload, n_metrics),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload, metrics),
    &org__eclipse__tahu__protobuf__payload__metric__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload, has_seq),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload, seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uuid",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload, uuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload, has_body),
    offsetof(Org__Eclipse__Tahu__Protobuf__Payload, body),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned org__eclipse__tahu__protobuf__payload__field_indices_by_name[] = {
  4,   /* field[4] = body */
  1,   /* field[1] = metrics */
  2,   /* field[2] = seq */
  0,   /* field[0] = timestamp */
  3,   /* field[3] = uuid */
};
static const ProtobufCIntRange org__eclipse__tahu__protobuf__payload__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "org.eclipse.tahu.protobuf.Payload",
  "Payload",
  "Org__Eclipse__Tahu__Protobuf__Payload",
  "org.eclipse.tahu.protobuf",
  sizeof(Org__Eclipse__Tahu__Protobuf__Payload),
  5,
  org__eclipse__tahu__protobuf__payload__field_descriptors,
  org__eclipse__tahu__protobuf__payload__field_indices_by_name,
  1,  org__eclipse__tahu__protobuf__payload__number_ranges,
  (ProtobufCMessageInit) org__eclipse__tahu__protobuf__payload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue org__eclipse__tahu__protobuf__data_type__enum_values_by_number[35] =
{
  { "Unknown", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Unknown", 0 },
  { "Int8", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Int8", 1 },
  { "Int16", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Int16", 2 },
  { "Int32", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Int32", 3 },
  { "Int64", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Int64", 4 },
  { "UInt8", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__UInt8", 5 },
  { "UInt16", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__UInt16", 6 },
  { "UInt32", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__UInt32", 7 },
  { "UInt64", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__UInt64", 8 },
  { "Float", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Float", 9 },
  { "Double", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Double", 10 },
  { "Boolean", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Boolean", 11 },
  { "String", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__String", 12 },
  { "DateTime", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__DateTime", 13 },
  { "Text", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Text", 14 },
  { "UUID", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__UUID", 15 },
  { "DataSet", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__DataSet", 16 },
  { "Bytes", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Bytes", 17 },
  { "File", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__File", 18 },
  { "Template", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Template", 19 },
  { "PropertySet", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__PropertySet", 20 },
  { "PropertySetList", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__PropertySetList", 21 },
  { "Int8Array", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Int8Array", 22 },
  { "Int16Array", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Int16Array", 23 },
  { "Int32Array", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Int32Array", 24 },
  { "Int64Array", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Int64Array", 25 },
  { "UInt8Array", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__UInt8Array", 26 },
  { "UInt16Array", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__UInt16Array", 27 },
  { "UInt32Array", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__UInt32Array", 28 },
  { "UInt64Array", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__UInt64Array", 29 },
  { "FloatArray", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__FloatArray", 30 },
  { "DoubleArray", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__DoubleArray", 31 },
  { "BooleanArray", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__BooleanArray", 32 },
  { "StringArray", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__StringArray", 33 },
  { "DateTimeArray", "ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__DateTimeArray", 34 },
};
static const ProtobufCIntRange org__eclipse__tahu__protobuf__data_type__value_ranges[] = {
{0, 0},{0, 35}
};
static const ProtobufCEnumValueIndex org__eclipse__tahu__protobuf__data_type__enum_values_by_name[35] =
{
  { "Boolean", 11 },
  { "BooleanArray", 32 },
  { "Bytes", 17 },
  { "DataSet", 16 },
  { "DateTime", 13 },
  { "DateTimeArray", 34 },
  { "Double", 10 },
  { "DoubleArray", 31 },
  { "File", 18 },
  { "Float", 9 },
  { "FloatArray", 30 },
  { "Int16", 2 },
  { "Int16Array", 23 },
  { "Int32", 3 },
  { "Int32Array", 24 },
  { "Int64", 4 },
  { "Int64Array", 25 },
  { "Int8", 1 },
  { "Int8Array", 22 },
  { "PropertySet", 20 },
  { "PropertySetList", 21 },
  { "String", 12 },
  { "StringArray", 33 },
  { "Template", 19 },
  { "Text", 14 },
  { "UInt16", 6 },
  { "UInt16Array", 27 },
  { "UInt32", 7 },
  { "UInt32Array", 28 },
  { "UInt64", 8 },
  { "UInt64Array", 29 },
  { "UInt8", 5 },
  { "UInt8Array", 26 },
  { "UUID", 15 },
  { "Unknown", 0 },
};
const ProtobufCEnumDescriptor org__eclipse__tahu__protobuf__data_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "org.eclipse.tahu.protobuf.DataType",
  "DataType",
  "Org__Eclipse__Tahu__Protobuf__DataType",
  "org.eclipse.tahu.protobuf",
  35,
  org__eclipse__tahu__protobuf__data_type__enum_values_by_number,
  35,
  org__eclipse__tahu__protobuf__data_type__enum_values_by_name,
  1,
  org__eclipse__tahu__protobuf__data_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
