/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sparkplug_b.proto */

#ifndef PROTOBUF_C_sparkplug_5fb_2eproto__INCLUDED
#define PROTOBUF_C_sparkplug_5fb_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Org__Eclipse__Tahu__Protobuf__Payload Org__Eclipse__Tahu__Protobuf__Payload;
typedef struct Org__Eclipse__Tahu__Protobuf__Payload__Template Org__Eclipse__Tahu__Protobuf__Payload__Template;
typedef struct Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter;
typedef struct Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter__ParameterValueExtension Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter__ParameterValueExtension;
typedef struct Org__Eclipse__Tahu__Protobuf__Payload__DataSet Org__Eclipse__Tahu__Protobuf__Payload__DataSet;
typedef struct Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue;
typedef struct Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue__DataSetValueExtension Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue__DataSetValueExtension;
typedef struct Org__Eclipse__Tahu__Protobuf__Payload__DataSet__Row Org__Eclipse__Tahu__Protobuf__Payload__DataSet__Row;
typedef struct Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue;
typedef struct Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue__PropertyValueExtension Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue__PropertyValueExtension;
typedef struct Org__Eclipse__Tahu__Protobuf__Payload__PropertySet Org__Eclipse__Tahu__Protobuf__Payload__PropertySet;
typedef struct Org__Eclipse__Tahu__Protobuf__Payload__PropertySetList Org__Eclipse__Tahu__Protobuf__Payload__PropertySetList;
typedef struct Org__Eclipse__Tahu__Protobuf__Payload__MetaData Org__Eclipse__Tahu__Protobuf__Payload__MetaData;
typedef struct Org__Eclipse__Tahu__Protobuf__Payload__Metric Org__Eclipse__Tahu__Protobuf__Payload__Metric;
typedef struct Org__Eclipse__Tahu__Protobuf__Payload__Metric__MetricValueExtension Org__Eclipse__Tahu__Protobuf__Payload__Metric__MetricValueExtension;


/* --- enums --- */

typedef enum _Org__Eclipse__Tahu__Protobuf__DataType {
  /*
   * Unknown placeholder for future expansion.
   */
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Unknown = 0,
  /*
   * Basic Types
   */
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Int8 = 1,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Int16 = 2,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Int32 = 3,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Int64 = 4,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__UInt8 = 5,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__UInt16 = 6,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__UInt32 = 7,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__UInt64 = 8,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Float = 9,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Double = 10,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Boolean = 11,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__String = 12,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__DateTime = 13,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Text = 14,
  /*
   * Additional Metric Types
   */
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__UUID = 15,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__DataSet = 16,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Bytes = 17,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__File = 18,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Template = 19,
  /*
   * Additional PropertyValue Types
   */
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__PropertySet = 20,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__PropertySetList = 21,
  /*
   * Array Types
   */
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Int8Array = 22,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Int16Array = 23,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Int32Array = 24,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__Int64Array = 25,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__UInt8Array = 26,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__UInt16Array = 27,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__UInt32Array = 28,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__UInt64Array = 29,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__FloatArray = 30,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__DoubleArray = 31,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__BooleanArray = 32,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__StringArray = 33,
  ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE__DateTimeArray = 34
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ORG__ECLIPSE__TAHU__PROTOBUF__DATA_TYPE)
} Org__Eclipse__Tahu__Protobuf__DataType;

/* --- messages --- */

struct  Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter__ParameterValueExtension
{
  ProtobufCMessage base;
};
#define ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__TEMPLATE__PARAMETER__PARAMETER_VALUE_EXTENSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&org__eclipse__tahu__protobuf__payload__template__parameter__parameter_value_extension__descriptor) \
 }


typedef enum {
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__TEMPLATE__PARAMETER__VALUE__NOT_SET = 0,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__TEMPLATE__PARAMETER__VALUE_INT_VALUE = 3,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__TEMPLATE__PARAMETER__VALUE_LONG_VALUE = 4,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__TEMPLATE__PARAMETER__VALUE_FLOAT_VALUE = 5,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__TEMPLATE__PARAMETER__VALUE_DOUBLE_VALUE = 6,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__TEMPLATE__PARAMETER__VALUE_BOOLEAN_VALUE = 7,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__TEMPLATE__PARAMETER__VALUE_STRING_VALUE = 8,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__TEMPLATE__PARAMETER__VALUE_EXTENSION_VALUE = 9
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__TEMPLATE__PARAMETER__VALUE__CASE)
} Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter__ValueCase;

struct  Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter
{
  ProtobufCMessage base;
  char *name;
  protobuf_c_boolean has_type;
  uint32_t type;
  Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter__ValueCase value_case;
  union {
    double double_value;
    uint64_t long_value;
    char *string_value;
    Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter__ParameterValueExtension *extension_value;
    float float_value;
    uint32_t int_value;
    protobuf_c_boolean boolean_value;
  };
};
#define ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__TEMPLATE__PARAMETER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&org__eclipse__tahu__protobuf__payload__template__parameter__descriptor) \
, NULL, 0, 0, ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__TEMPLATE__PARAMETER__VALUE__NOT_SET, {0} }


struct  Org__Eclipse__Tahu__Protobuf__Payload__Template
{
  ProtobufCMessage base;
  /*
   * The version of the Template to prevent mismatches
   */
  char *version;
  /*
   * Each metric includes a name, datatype, and optionally a value
   */
  size_t n_metrics;
  Org__Eclipse__Tahu__Protobuf__Payload__Metric **metrics;
  size_t n_parameters;
  Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter **parameters;
  /*
   * MUST be a reference to a template definition if this is an instance (i.e. the name of the template definition) - MUST be omitted for template definitions
   */
  char *template_ref;
  protobuf_c_boolean has_is_definition;
  protobuf_c_boolean is_definition;
};
#define ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__TEMPLATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&org__eclipse__tahu__protobuf__payload__template__descriptor) \
, NULL, 0,NULL, 0,NULL, NULL, 0, 0 }


struct  Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue__DataSetValueExtension
{
  ProtobufCMessage base;
};
#define ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__DATA_SET__DATA_SET_VALUE__DATA_SET_VALUE_EXTENSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&org__eclipse__tahu__protobuf__payload__data_set__data_set_value__data_set_value_extension__descriptor) \
 }


typedef enum {
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__DATA_SET__DATA_SET_VALUE__VALUE__NOT_SET = 0,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__DATA_SET__DATA_SET_VALUE__VALUE_INT_VALUE = 1,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__DATA_SET__DATA_SET_VALUE__VALUE_LONG_VALUE = 2,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__DATA_SET__DATA_SET_VALUE__VALUE_FLOAT_VALUE = 3,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__DATA_SET__DATA_SET_VALUE__VALUE_DOUBLE_VALUE = 4,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__DATA_SET__DATA_SET_VALUE__VALUE_BOOLEAN_VALUE = 5,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__DATA_SET__DATA_SET_VALUE__VALUE_STRING_VALUE = 6,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__DATA_SET__DATA_SET_VALUE__VALUE_EXTENSION_VALUE = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__DATA_SET__DATA_SET_VALUE__VALUE__CASE)
} Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue__ValueCase;

struct  Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue
{
  ProtobufCMessage base;
  Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue__ValueCase value_case;
  union {
    double double_value;
    uint64_t long_value;
    char *string_value;
    Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue__DataSetValueExtension *extension_value;
    float float_value;
    uint32_t int_value;
    protobuf_c_boolean boolean_value;
  };
};
#define ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__DATA_SET__DATA_SET_VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&org__eclipse__tahu__protobuf__payload__data_set__data_set_value__descriptor) \
, ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__DATA_SET__DATA_SET_VALUE__VALUE__NOT_SET, {0} }


struct  Org__Eclipse__Tahu__Protobuf__Payload__DataSet__Row
{
  ProtobufCMessage base;
  size_t n_elements;
  Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue **elements;
};
#define ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__DATA_SET__ROW__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&org__eclipse__tahu__protobuf__payload__data_set__row__descriptor) \
, 0,NULL }


struct  Org__Eclipse__Tahu__Protobuf__Payload__DataSet
{
  ProtobufCMessage base;
  protobuf_c_boolean has_num_of_columns;
  uint64_t num_of_columns;
  size_t n_columns;
  char **columns;
  size_t n_types;
  uint32_t *types;
  size_t n_rows;
  Org__Eclipse__Tahu__Protobuf__Payload__DataSet__Row **rows;
};
#define ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__DATA_SET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&org__eclipse__tahu__protobuf__payload__data_set__descriptor) \
, 0, 0, 0,NULL, 0,NULL, 0,NULL }


struct  Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue__PropertyValueExtension
{
  ProtobufCMessage base;
};
#define ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__PROPERTY_VALUE__PROPERTY_VALUE_EXTENSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&org__eclipse__tahu__protobuf__payload__property_value__property_value_extension__descriptor) \
 }


typedef enum {
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__PROPERTY_VALUE__VALUE__NOT_SET = 0,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__PROPERTY_VALUE__VALUE_INT_VALUE = 3,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__PROPERTY_VALUE__VALUE_LONG_VALUE = 4,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__PROPERTY_VALUE__VALUE_FLOAT_VALUE = 5,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__PROPERTY_VALUE__VALUE_DOUBLE_VALUE = 6,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__PROPERTY_VALUE__VALUE_BOOLEAN_VALUE = 7,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__PROPERTY_VALUE__VALUE_STRING_VALUE = 8,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__PROPERTY_VALUE__VALUE_PROPERTYSET_VALUE = 9,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__PROPERTY_VALUE__VALUE_PROPERTYSETS_VALUE = 10,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__PROPERTY_VALUE__VALUE_EXTENSION_VALUE = 11
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__PROPERTY_VALUE__VALUE__CASE)
} Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue__ValueCase;

struct  Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue
{
  ProtobufCMessage base;
  protobuf_c_boolean has_type;
  uint32_t type;
  protobuf_c_boolean has_is_null;
  protobuf_c_boolean is_null;
  Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue__ValueCase value_case;
  union {
    double double_value;
    uint64_t long_value;
    char *string_value;
    Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue__PropertyValueExtension *extension_value;
    Org__Eclipse__Tahu__Protobuf__Payload__PropertySet *propertyset_value;
    /*
     * List of Property Values
     */
    Org__Eclipse__Tahu__Protobuf__Payload__PropertySetList *propertysets_value;
    float float_value;
    uint32_t int_value;
    protobuf_c_boolean boolean_value;
  };
};
#define ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__PROPERTY_VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&org__eclipse__tahu__protobuf__payload__property_value__descriptor) \
, 0, 0, 0, 0, ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__PROPERTY_VALUE__VALUE__NOT_SET, {0} }


struct  Org__Eclipse__Tahu__Protobuf__Payload__PropertySet
{
  ProtobufCMessage base;
  /*
   * Names of the properties
   */
  size_t n_keys;
  char **keys;
  size_t n_values;
  Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue **values;
};
#define ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__PROPERTY_SET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&org__eclipse__tahu__protobuf__payload__property_set__descriptor) \
, 0,NULL, 0,NULL }


struct  Org__Eclipse__Tahu__Protobuf__Payload__PropertySetList
{
  ProtobufCMessage base;
  size_t n_propertyset;
  Org__Eclipse__Tahu__Protobuf__Payload__PropertySet **propertyset;
};
#define ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__PROPERTY_SET_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&org__eclipse__tahu__protobuf__payload__property_set_list__descriptor) \
, 0,NULL }


struct  Org__Eclipse__Tahu__Protobuf__Payload__MetaData
{
  ProtobufCMessage base;
  /*
   * Bytes specific metadata
   */
  protobuf_c_boolean has_is_multi_part;
  protobuf_c_boolean is_multi_part;
  /*
   * General metadata
   */
  /*
   * Content/Media type
   */
  char *content_type;
  /*
   * File size, String size, Multi-part size, etc
   */
  protobuf_c_boolean has_size;
  uint64_t size;
  /*
   * Sequence number for multi-part messages
   */
  protobuf_c_boolean has_seq;
  uint64_t seq;
  /*
   * File metadata
   */
  /*
   * File name
   */
  char *file_name;
  /*
   * File type (i.e. xml, json, txt, cpp, etc)
   */
  char *file_type;
  /*
   * md5 of data
   */
  char *md5;
  /*
   * Catchalls and future expansion
   */
  /*
   * Could be anything such as json or xml of custom properties
   */
  char *description;
};
#define ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__META_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&org__eclipse__tahu__protobuf__payload__meta_data__descriptor) \
, 0, 0, NULL, 0, 0, 0, 0, NULL, NULL, NULL, NULL }


struct  Org__Eclipse__Tahu__Protobuf__Payload__Metric__MetricValueExtension
{
  ProtobufCMessage base;
};
#define ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__METRIC__METRIC_VALUE_EXTENSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&org__eclipse__tahu__protobuf__payload__metric__metric_value_extension__descriptor) \
 }


typedef enum {
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__METRIC__VALUE__NOT_SET = 0,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__METRIC__VALUE_INT_VALUE = 10,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__METRIC__VALUE_LONG_VALUE = 11,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__METRIC__VALUE_FLOAT_VALUE = 12,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__METRIC__VALUE_DOUBLE_VALUE = 13,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__METRIC__VALUE_BOOLEAN_VALUE = 14,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__METRIC__VALUE_STRING_VALUE = 15,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__METRIC__VALUE_BYTES_VALUE = 16,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__METRIC__VALUE_DATASET_VALUE = 17,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__METRIC__VALUE_TEMPLATE_VALUE = 18,
  ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__METRIC__VALUE_EXTENSION_VALUE = 19
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__METRIC__VALUE__CASE)
} Org__Eclipse__Tahu__Protobuf__Payload__Metric__ValueCase;

struct  Org__Eclipse__Tahu__Protobuf__Payload__Metric
{
  ProtobufCMessage base;
  /*
   * Metric name - should only be included on birth
   */
  char *name;
  /*
   * Metric alias - tied to name on birth and included in all later DATA messages
   */
  protobuf_c_boolean has_alias;
  uint64_t alias;
  /*
   * Timestamp associated with data acquisition time
   */
  protobuf_c_boolean has_timestamp;
  uint64_t timestamp;
  /*
   * DataType of the metric/tag value
   */
  protobuf_c_boolean has_datatype;
  uint32_t datatype;
  /*
   * If this is historical data and should not update real time tag
   */
  protobuf_c_boolean has_is_historical;
  protobuf_c_boolean is_historical;
  /*
   * Tells consuming clients such as MQTT Engine to not store this as a tag
   */
  protobuf_c_boolean has_is_transient;
  protobuf_c_boolean is_transient;
  /*
   * If this is null - explicitly say so rather than using -1, false, etc for some datatypes.
   */
  protobuf_c_boolean has_is_null;
  protobuf_c_boolean is_null;
  /*
   * Metadata for the payload
   */
  Org__Eclipse__Tahu__Protobuf__Payload__MetaData *metadata;
  Org__Eclipse__Tahu__Protobuf__Payload__PropertySet *properties;
  Org__Eclipse__Tahu__Protobuf__Payload__Metric__ValueCase value_case;
  union {
    /*
     * Bytes, File
     */
    ProtobufCBinaryData bytes_value;
    double double_value;
    uint64_t long_value;
    char *string_value;
    Org__Eclipse__Tahu__Protobuf__Payload__DataSet *dataset_value;
    Org__Eclipse__Tahu__Protobuf__Payload__Metric__MetricValueExtension *extension_value;
    Org__Eclipse__Tahu__Protobuf__Payload__Template *template_value;
    float float_value;
    uint32_t int_value;
    protobuf_c_boolean boolean_value;
  };
};
#define ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__METRIC__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&org__eclipse__tahu__protobuf__payload__metric__descriptor) \
, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__METRIC__VALUE__NOT_SET, { {0} } }


struct  Org__Eclipse__Tahu__Protobuf__Payload
{
  ProtobufCMessage base;
  /*
   * Timestamp at message sending time
   */
  protobuf_c_boolean has_timestamp;
  uint64_t timestamp;
  /*
   * Repeated forever - no limit in Google Protobufs
   */
  size_t n_metrics;
  Org__Eclipse__Tahu__Protobuf__Payload__Metric **metrics;
  /*
   * Sequence number
   */
  protobuf_c_boolean has_seq;
  uint64_t seq;
  /*
   * UUID to track message type in terms of schema definitions
   */
  char *uuid;
  /*
   * To optionally bypass the whole definition above
   */
  protobuf_c_boolean has_body;
  ProtobufCBinaryData body;
};
#define ORG__ECLIPSE__TAHU__PROTOBUF__PAYLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&org__eclipse__tahu__protobuf__payload__descriptor) \
, 0, 0, 0,NULL, 0, 0, NULL, 0, {0,NULL} }


/* Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter__ParameterValueExtension methods */
void   org__eclipse__tahu__protobuf__payload__template__parameter__parameter_value_extension__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter__ParameterValueExtension         *message);
/* Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter methods */
void   org__eclipse__tahu__protobuf__payload__template__parameter__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter         *message);
/* Org__Eclipse__Tahu__Protobuf__Payload__Template methods */
void   org__eclipse__tahu__protobuf__payload__template__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__Template         *message);
/* Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue__DataSetValueExtension methods */
void   org__eclipse__tahu__protobuf__payload__data_set__data_set_value__data_set_value_extension__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue__DataSetValueExtension         *message);
/* Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue methods */
void   org__eclipse__tahu__protobuf__payload__data_set__data_set_value__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue         *message);
/* Org__Eclipse__Tahu__Protobuf__Payload__DataSet__Row methods */
void   org__eclipse__tahu__protobuf__payload__data_set__row__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__DataSet__Row         *message);
/* Org__Eclipse__Tahu__Protobuf__Payload__DataSet methods */
void   org__eclipse__tahu__protobuf__payload__data_set__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__DataSet         *message);
/* Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue__PropertyValueExtension methods */
void   org__eclipse__tahu__protobuf__payload__property_value__property_value_extension__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue__PropertyValueExtension         *message);
/* Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue methods */
void   org__eclipse__tahu__protobuf__payload__property_value__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue         *message);
/* Org__Eclipse__Tahu__Protobuf__Payload__PropertySet methods */
void   org__eclipse__tahu__protobuf__payload__property_set__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__PropertySet         *message);
/* Org__Eclipse__Tahu__Protobuf__Payload__PropertySetList methods */
void   org__eclipse__tahu__protobuf__payload__property_set_list__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__PropertySetList         *message);
/* Org__Eclipse__Tahu__Protobuf__Payload__MetaData methods */
void   org__eclipse__tahu__protobuf__payload__meta_data__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__MetaData         *message);
/* Org__Eclipse__Tahu__Protobuf__Payload__Metric__MetricValueExtension methods */
void   org__eclipse__tahu__protobuf__payload__metric__metric_value_extension__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__Metric__MetricValueExtension         *message);
/* Org__Eclipse__Tahu__Protobuf__Payload__Metric methods */
void   org__eclipse__tahu__protobuf__payload__metric__init
                     (Org__Eclipse__Tahu__Protobuf__Payload__Metric         *message);
/* Org__Eclipse__Tahu__Protobuf__Payload methods */
void   org__eclipse__tahu__protobuf__payload__init
                     (Org__Eclipse__Tahu__Protobuf__Payload         *message);
size_t org__eclipse__tahu__protobuf__payload__get_packed_size
                     (const Org__Eclipse__Tahu__Protobuf__Payload   *message);
size_t org__eclipse__tahu__protobuf__payload__pack
                     (const Org__Eclipse__Tahu__Protobuf__Payload   *message,
                      uint8_t             *out);
size_t org__eclipse__tahu__protobuf__payload__pack_to_buffer
                     (const Org__Eclipse__Tahu__Protobuf__Payload   *message,
                      ProtobufCBuffer     *buffer);
Org__Eclipse__Tahu__Protobuf__Payload *
       org__eclipse__tahu__protobuf__payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   org__eclipse__tahu__protobuf__payload__free_unpacked
                     (Org__Eclipse__Tahu__Protobuf__Payload *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter__ParameterValueExtension_Closure)
                 (const Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter__ParameterValueExtension *message,
                  void *closure_data);
typedef void (*Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter_Closure)
                 (const Org__Eclipse__Tahu__Protobuf__Payload__Template__Parameter *message,
                  void *closure_data);
typedef void (*Org__Eclipse__Tahu__Protobuf__Payload__Template_Closure)
                 (const Org__Eclipse__Tahu__Protobuf__Payload__Template *message,
                  void *closure_data);
typedef void (*Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue__DataSetValueExtension_Closure)
                 (const Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue__DataSetValueExtension *message,
                  void *closure_data);
typedef void (*Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue_Closure)
                 (const Org__Eclipse__Tahu__Protobuf__Payload__DataSet__DataSetValue *message,
                  void *closure_data);
typedef void (*Org__Eclipse__Tahu__Protobuf__Payload__DataSet__Row_Closure)
                 (const Org__Eclipse__Tahu__Protobuf__Payload__DataSet__Row *message,
                  void *closure_data);
typedef void (*Org__Eclipse__Tahu__Protobuf__Payload__DataSet_Closure)
                 (const Org__Eclipse__Tahu__Protobuf__Payload__DataSet *message,
                  void *closure_data);
typedef void (*Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue__PropertyValueExtension_Closure)
                 (const Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue__PropertyValueExtension *message,
                  void *closure_data);
typedef void (*Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue_Closure)
                 (const Org__Eclipse__Tahu__Protobuf__Payload__PropertyValue *message,
                  void *closure_data);
typedef void (*Org__Eclipse__Tahu__Protobuf__Payload__PropertySet_Closure)
                 (const Org__Eclipse__Tahu__Protobuf__Payload__PropertySet *message,
                  void *closure_data);
typedef void (*Org__Eclipse__Tahu__Protobuf__Payload__PropertySetList_Closure)
                 (const Org__Eclipse__Tahu__Protobuf__Payload__PropertySetList *message,
                  void *closure_data);
typedef void (*Org__Eclipse__Tahu__Protobuf__Payload__MetaData_Closure)
                 (const Org__Eclipse__Tahu__Protobuf__Payload__MetaData *message,
                  void *closure_data);
typedef void (*Org__Eclipse__Tahu__Protobuf__Payload__Metric__MetricValueExtension_Closure)
                 (const Org__Eclipse__Tahu__Protobuf__Payload__Metric__MetricValueExtension *message,
                  void *closure_data);
typedef void (*Org__Eclipse__Tahu__Protobuf__Payload__Metric_Closure)
                 (const Org__Eclipse__Tahu__Protobuf__Payload__Metric *message,
                  void *closure_data);
typedef void (*Org__Eclipse__Tahu__Protobuf__Payload_Closure)
                 (const Org__Eclipse__Tahu__Protobuf__Payload *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    org__eclipse__tahu__protobuf__data_type__descriptor;
extern const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__descriptor;
extern const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__template__descriptor;
extern const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__template__parameter__descriptor;
extern const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__template__parameter__parameter_value_extension__descriptor;
extern const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__data_set__descriptor;
extern const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__data_set__data_set_value__descriptor;
extern const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__data_set__data_set_value__data_set_value_extension__descriptor;
extern const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__data_set__row__descriptor;
extern const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__property_value__descriptor;
extern const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__property_value__property_value_extension__descriptor;
extern const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__property_set__descriptor;
extern const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__property_set_list__descriptor;
extern const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__meta_data__descriptor;
extern const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__metric__descriptor;
extern const ProtobufCMessageDescriptor org__eclipse__tahu__protobuf__payload__metric__metric_value_extension__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sparkplug_5fb_2eproto__INCLUDED */
