<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sparkplug_b.proto

namespace Org\Eclipse\Tahu\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Org\Eclipse\Tahu\Protobuf\Payload\PropertySet instead.
     * @deprecated
     */
    class Payload_PropertySet {}
}
class_exists(Payload\PropertySet::class);
@trigger_error('Org\Eclipse\Tahu\Protobuf\Payload_PropertySet is deprecated and will be removed in the next major release. Use Org\Eclipse\Tahu\Protobuf\Payload\PropertySet instead', E_USER_DEPRECATED);

