<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sparkplug_b.proto

namespace Org\Eclipse\Tahu\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Org\Eclipse\Tahu\Protobuf\Payload\MetaData instead.
     * @deprecated
     */
    class Payload_MetaData {}
}
class_exists(Payload\MetaData::class);
@trigger_error('Org\Eclipse\Tahu\Protobuf\Payload_MetaData is deprecated and will be removed in the next major release. Use Org\Eclipse\Tahu\Protobuf\Payload\MetaData instead', E_USER_DEPRECATED);

