<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sparkplug_b.proto

namespace Org\Eclipse\Tahu\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>org.eclipse.tahu.protobuf.Payload</code>
 */
class Payload extends \Google\Protobuf\Internal\Message
{
    /**
     * Timestamp at message sending time
     *
     * Generated from protobuf field <code>optional uint64 timestamp = 1;</code>
     */
    protected $timestamp = null;
    /**
     * Repeated forever - no limit in Google Protobufs
     *
     * Generated from protobuf field <code>repeated .org.eclipse.tahu.protobuf.Payload.Metric metrics = 2;</code>
     */
    private $metrics;
    /**
     * Sequence number
     *
     * Generated from protobuf field <code>optional uint64 seq = 3;</code>
     */
    protected $seq = null;
    /**
     * UUID to track message type in terms of schema definitions
     *
     * Generated from protobuf field <code>optional string uuid = 4;</code>
     */
    protected $uuid = null;
    /**
     * To optionally bypass the whole definition above
     *
     * Generated from protobuf field <code>optional bytes body = 5;</code>
     */
    protected $body = null;
    /**
     * extensions                      6 to max;   // For third party extensions // For proto2
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any extensions = 6;</code>
     */
    private $extensions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $timestamp
     *           Timestamp at message sending time
     *     @type array<\Org\Eclipse\Tahu\Protobuf\Payload\Metric>|\Google\Protobuf\Internal\RepeatedField $metrics
     *           Repeated forever - no limit in Google Protobufs
     *     @type int|string $seq
     *           Sequence number
     *     @type string $uuid
     *           UUID to track message type in terms of schema definitions
     *     @type string $body
     *           To optionally bypass the whole definition above
     *     @type array<\Google\Protobuf\Any>|\Google\Protobuf\Internal\RepeatedField $extensions
     *           extensions                      6 to max;   // For third party extensions // For proto2
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SparkplugB::initOnce();
        parent::__construct($data);
    }

    /**
     * Timestamp at message sending time
     *
     * Generated from protobuf field <code>optional uint64 timestamp = 1;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return isset($this->timestamp) ? $this->timestamp : 0;
    }

    public function hasTimestamp()
    {
        return isset($this->timestamp);
    }

    public function clearTimestamp()
    {
        unset($this->timestamp);
    }

    /**
     * Timestamp at message sending time
     *
     * Generated from protobuf field <code>optional uint64 timestamp = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Repeated forever - no limit in Google Protobufs
     *
     * Generated from protobuf field <code>repeated .org.eclipse.tahu.protobuf.Payload.Metric metrics = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMetrics()
    {
        return $this->metrics;
    }

    /**
     * Repeated forever - no limit in Google Protobufs
     *
     * Generated from protobuf field <code>repeated .org.eclipse.tahu.protobuf.Payload.Metric metrics = 2;</code>
     * @param array<\Org\Eclipse\Tahu\Protobuf\Payload\Metric>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMetrics($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Org\Eclipse\Tahu\Protobuf\Payload\Metric::class);
        $this->metrics = $arr;

        return $this;
    }

    /**
     * Sequence number
     *
     * Generated from protobuf field <code>optional uint64 seq = 3;</code>
     * @return int|string
     */
    public function getSeq()
    {
        return isset($this->seq) ? $this->seq : 0;
    }

    public function hasSeq()
    {
        return isset($this->seq);
    }

    public function clearSeq()
    {
        unset($this->seq);
    }

    /**
     * Sequence number
     *
     * Generated from protobuf field <code>optional uint64 seq = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSeq($var)
    {
        GPBUtil::checkUint64($var);
        $this->seq = $var;

        return $this;
    }

    /**
     * UUID to track message type in terms of schema definitions
     *
     * Generated from protobuf field <code>optional string uuid = 4;</code>
     * @return string
     */
    public function getUuid()
    {
        return isset($this->uuid) ? $this->uuid : '';
    }

    public function hasUuid()
    {
        return isset($this->uuid);
    }

    public function clearUuid()
    {
        unset($this->uuid);
    }

    /**
     * UUID to track message type in terms of schema definitions
     *
     * Generated from protobuf field <code>optional string uuid = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uuid = $var;

        return $this;
    }

    /**
     * To optionally bypass the whole definition above
     *
     * Generated from protobuf field <code>optional bytes body = 5;</code>
     * @return string
     */
    public function getBody()
    {
        return isset($this->body) ? $this->body : '';
    }

    public function hasBody()
    {
        return isset($this->body);
    }

    public function clearBody()
    {
        unset($this->body);
    }

    /**
     * To optionally bypass the whole definition above
     *
     * Generated from protobuf field <code>optional bytes body = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->body = $var;

        return $this;
    }

    /**
     * extensions                      6 to max;   // For third party extensions // For proto2
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any extensions = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    /**
     * extensions                      6 to max;   // For third party extensions // For proto2
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any extensions = 6;</code>
     * @param array<\Google\Protobuf\Any>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExtensions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Any::class);
        $this->extensions = $arr;

        return $this;
    }

}

