<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sparkplug_b.proto

namespace Org\Eclipse\Tahu\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Org\Eclipse\Tahu\Protobuf\Payload\Template\Parameter instead.
     * @deprecated
     */
    class Payload_Template_Parameter {}
}
class_exists(Payload\Template\Parameter::class);
@trigger_error('Org\Eclipse\Tahu\Protobuf\Payload_Template_Parameter is deprecated and will be removed in the next major release. Use Org\Eclipse\Tahu\Protobuf\Payload\Template\Parameter instead', E_USER_DEPRECATED);

