<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sparkplug_b.proto

namespace Org\Eclipse\Tahu\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Org\Eclipse\Tahu\Protobuf\Payload\Template instead.
     * @deprecated
     */
    class Payload_Template {}
}
class_exists(Payload\Template::class);
@trigger_error('Org\Eclipse\Tahu\Protobuf\Payload_Template is deprecated and will be removed in the next major release. Use Org\Eclipse\Tahu\Protobuf\Payload\Template instead', E_USER_DEPRECATED);

