<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sparkplug_b.proto

namespace Org\Eclipse\Tahu\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Org\Eclipse\Tahu\Protobuf\Payload\Metric instead.
     * @deprecated
     */
    class Payload_Metric {}
}
class_exists(Payload\Metric::class);
@trigger_error('Org\Eclipse\Tahu\Protobuf\Payload_Metric is deprecated and will be removed in the next major release. Use Org\Eclipse\Tahu\Protobuf\Payload\Metric instead', E_USER_DEPRECATED);

