<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sparkplug_b.proto

namespace Org\Eclipse\Tahu\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Org\Eclipse\Tahu\Protobuf\Payload\Template\Parameter\ParameterValueExtension instead.
     * @deprecated
     */
    class Payload_Template_Parameter_ParameterValueExtension {}
}
class_exists(Payload\Template\Parameter\ParameterValueExtension::class);
@trigger_error('Org\Eclipse\Tahu\Protobuf\Payload_Template_Parameter_ParameterValueExtension is deprecated and will be removed in the next major release. Use Org\Eclipse\Tahu\Protobuf\Payload\Template\Parameter\ParameterValueExtension instead', E_USER_DEPRECATED);

