<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sparkplug_b.proto

namespace Org\Eclipse\Tahu\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Org\Eclipse\Tahu\Protobuf\Payload\PropertyValue\PropertyValueExtension instead.
     * @deprecated
     */
    class Payload_PropertyValue_PropertyValueExtension {}
}
class_exists(Payload\PropertyValue\PropertyValueExtension::class);
@trigger_error('Org\Eclipse\Tahu\Protobuf\Payload_PropertyValue_PropertyValueExtension is deprecated and will be removed in the next major release. Use Org\Eclipse\Tahu\Protobuf\Payload\PropertyValue\PropertyValueExtension instead', E_USER_DEPRECATED);

