<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sparkplug_b.proto

namespace Org\Eclipse\Tahu\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use Org\Eclipse\Tahu\Protobuf\Payload\PropertyValue instead.
     * @deprecated
     */
    class Payload_PropertyValue {}
}
class_exists(Payload\PropertyValue::class);
@trigger_error('Org\Eclipse\Tahu\Protobuf\Payload_PropertyValue is deprecated and will be removed in the next major release. Use Org\Eclipse\Tahu\Protobuf\Payload\PropertyValue instead', E_USER_DEPRECATED);

