<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sparkplug_b.proto

namespace Org\Eclipse\Tahu\Protobuf\Payload\PropertyValue;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>org.eclipse.tahu.protobuf.Payload.PropertyValue.PropertyValueExtension</code>
 */
class PropertyValueExtension extends \Google\Protobuf\Internal\Message
{
    /**
     * extensions                             1 to max; // For proto2
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any extensions = 1;</code>
     */
    private $extensions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Google\Protobuf\Any>|\Google\Protobuf\Internal\RepeatedField $extensions
     *           extensions                             1 to max; // For proto2
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SparkplugB::initOnce();
        parent::__construct($data);
    }

    /**
     * extensions                             1 to max; // For proto2
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any extensions = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    /**
     * extensions                             1 to max; // For proto2
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any extensions = 1;</code>
     * @param array<\Google\Protobuf\Any>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExtensions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Any::class);
        $this->extensions = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PropertyValueExtension::class, \Org\Eclipse\Tahu\Protobuf\Payload_PropertyValue_PropertyValueExtension::class);

